"""Slice the generated, keyed 4x6 atlas into consistently grounded Unity sprites.

Artwork is generated by image_gen; this script only prepares sprite imports.
Run after the imagegen skill's remove_chroma_key.py helper.
"""
from pathlib import Path
from PIL import Image
import argparse
import json
import uuid

POSES = ("Idle", "Move", "Melee", "Cast", "Reflection", "Death")
ROOT = Path(__file__).resolve().parents[1]


def build(atlas_path: Path, destination: Path):
    atlas = Image.open(atlas_path).convert("RGBA")
    assert atlas.width * 6 == atlas.height * 4, "Expected 4-column, 6-row atlas"
    cell = atlas.width // 4
    assert atlas.width % 4 == 0 and atlas.height % 6 == 0
    destination.mkdir(parents=True, exist_ok=True)
    template = (ROOT / "Assets/_Project/Resources/FinalBoss/PhaseThree/MobileCerebrum.png.meta").read_text()
    preview = Image.new("RGBA", (512 * 4, 512 * 6))
    report = []
    # One scale for all frames, including death. Leave padding for claw tips.
    scale = 448 / cell
    for row, pose in enumerate(POSES):
        folder = destination / pose
        folder.mkdir(exist_ok=True)
        folder_meta = folder.with_suffix(".meta")
        if not folder_meta.exists():
            folder_meta.write_text(f"fileFormatVersion: 2\nguid: {uuid.uuid4().hex}\nfolderAsset: yes\nDefaultImporter:\n  externalObjects: {{}}\n  userData:\n  assetBundleName:\n  assetBundleVariant:\n")
        for column in range(4):
            frame = atlas.crop((column * cell, row * cell, (column + 1) * cell, (row + 1) * cell))
            bbox = frame.getchannel("A").point(lambda value: 255 if value > 32 else 0).getbbox()
            assert bbox and bbox[2] - bbox[0] > cell * .35, f"Empty frame {pose}/{column}"
            # Keep horizontal registration; align only the ground contact, so a corpse
            # collapses toward the same floor instead of floating at the cell centre.
            cropped = frame.crop((0, 0, cell, bbox[3]))
            cropped = cropped.resize((448, round(cropped.height * scale)), Image.Resampling.NEAREST)
            output = Image.new("RGBA", (512, 512))
            output.paste(cropped, (32, 471 - cropped.height))
            name = f"{pose}_{column:02d}.png"
            path = folder / name
            output.save(path)
            meta = Path(str(path) + ".meta")
            if not meta.exists():
                metadata = template.replace("guid: 29042c30f2e84656b6f5c4f5d59f3bce", f"guid: {uuid.uuid4().hex}")
                metadata = metadata.replace("spriteID: 29042c30f2e84656b6f5c4f5d59f3bce", f"spriteID: {uuid.uuid4().hex}")
                metadata = metadata.replace("y: 0.06", "y: 0.08").replace("maxTextureSize: 4096", "maxTextureSize: 1024")
                meta.write_text(metadata)
            alpha = output.getchannel("A")
            assert all(alpha.getpixel(corner) == 0 for corner in ((0, 0), (511, 0), (0, 511), (511, 511)))
            assert alpha.getbbox()[3] == 471, f"Incorrect ground contact for {name}"
            preview.paste(output, (column * 512, row * 512))
            report.append({"pose": pose, "frame": column, "source_bounds": bbox, "bounds": alpha.getbbox()})
    export = ROOT / "Exports/FinalBossConcepts/2026-10-05-animations"
    export.mkdir(parents=True, exist_ok=True)
    preview.save(export / "CerebrumAnimationsPreview.png")
    (export / "sprite-validation.json").write_text(json.dumps(report, indent=2))
    print(f"PASS: {len(report)} transparent 512x512 frames, common scale/baseline, six sequences")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--atlas", type=Path, default=ROOT / "Assets/_Project/Art/Generated/FinalBoss/CerebrumAnimations_v1.png")
    parser.add_argument("--out", type=Path, default=ROOT / "Assets/_Project/Resources/FinalBoss/PhaseThree/Animations")
    args = parser.parse_args()
    build(args.atlas, args.out)
